//
// Created by user on 01.08.20.
//

#ifndef JSONLD_CPP_CORE_LOADDOCUMENTOPTIONS_H
#define JSONLD_CPP_CORE_LOADDOCUMENTOPTIONS_H

class LoadDocumentOptions {

};

#endif //JSONLD_CPP_CORE_LOADDOCUMENTOPTIONS_H
